export const PRODUCTS = [
  {
    id: 1,
    image: "https://m.media-amazon.com/images/I/811u6QEwQxL._AC_SL1500_.jpg",
    name: "Sony Wireless Headphones WH-CH510: Wireless Bluetooth On-Ear Headset with Mic for Phone-Call, Black",
    description: [
      "Cancel out the world with smart noise cancellation",
      "Listen to your favorite tracks wirelessly with a Bluetooth wireless technology by pairing your smartphone or tablet",
      "30 millimeter driver unit for dynamic sound",
      "Swivel design for easy travel. Effective Range: Line of sight approx. 30 ft (10 m)",
      "Easy hands-free calling and voice assistant commands with microphone",
      "Voice assistant-compatible for easy access to your smartphone",
      "Next-generation USB type C charging",
    ],
    price: 14000,
  },
  {
    id: 2,
    image: "https://m.media-amazon.com/images/I/811u6QEwQxL._AC_SL1500_.jpg",
    name: "Sony Wireless Headphones WH-CH510: Wireless Bluetooth On-Ear Headset with Mic for Phone-Call, Black",
    description: [
      "Cancel out the world with smart noise cancellation",
      "Listen to your favorite tracks wirelessly with a Bluetooth wireless technology by pairing your smartphone or tablet",
      "30 millimeter driver unit for dynamic sound",
      "Swivel design for easy travel. Effective Range: Line of sight approx. 30 ft (10 m)",
      "Easy hands-free calling and voice assistant commands with microphone",
      "Voice assistant-compatible for easy access to your smartphone",
      "Next-generation USB type C charging",
    ],
    price: 14000,
  },
  {
    id: 3,
    image: "https://m.media-amazon.com/images/I/811u6QEwQxL._AC_SL1500_.jpg",
    name: "Sony Wireless Headphones WH-CH510: Wireless Bluetooth On-Ear Headset with Mic for Phone-Call, Black",
    description: [
      "Cancel out the world with smart noise cancellation",
      "Listen to your favorite tracks wirelessly with a Bluetooth wireless technology by pairing your smartphone or tablet",
      "30 millimeter driver unit for dynamic sound",
      "Swivel design for easy travel. Effective Range: Line of sight approx. 30 ft (10 m)",
      "Easy hands-free calling and voice assistant commands with microphone",
      "Voice assistant-compatible for easy access to your smartphone",
      "Next-generation USB type C charging",
    ],
    price: 14000,
  },
  {
    id: 4,
    image: "https://m.media-amazon.com/images/I/811u6QEwQxL._AC_SL1500_.jpg",
    name: "Sony Wireless Headphones WH-CH510: Wireless Bluetooth On-Ear Headset with Mic for Phone-Call, Black",
    description: [
      "Cancel out the world with smart noise cancellation",
      "Listen to your favorite tracks wirelessly with a Bluetooth wireless technology by pairing your smartphone or tablet",
      "30 millimeter driver unit for dynamic sound",
      "Swivel design for easy travel. Effective Range: Line of sight approx. 30 ft (10 m)",
      "Easy hands-free calling and voice assistant commands with microphone",
      "Voice assistant-compatible for easy access to your smartphone",
      "Next-generation USB type C charging",
    ],
    price: 14000,
  },
  {
    id: 5,
    image: "https://m.media-amazon.com/images/I/811u6QEwQxL._AC_SL1500_.jpg",
    name: "Sony Wireless Headphones WH-CH510: Wireless Bluetooth On-Ear Headset with Mic for Phone-Call, Black",
    description: [
      "Cancel out the world with smart noise cancellation",
      "Listen to your favorite tracks wirelessly with a Bluetooth wireless technology by pairing your smartphone or tablet",
      "30 millimeter driver unit for dynamic sound",
      "Swivel design for easy travel. Effective Range: Line of sight approx. 30 ft (10 m)",
      "Easy hands-free calling and voice assistant commands with microphone",
      "Voice assistant-compatible for easy access to your smartphone",
      "Next-generation USB type C charging",
    ],
    price: 14000,
  },
];
